In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv(r'D:\Python\california_housing_train.csv')

In [9]:
print(df)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
5        -114.58     33.63                29.0       1387.0           236.0   
6        -114.58     33.61                25.0       2907.0           680.0   
7        -114.59     34.83                41.0        812.0           168.0   
8        -114.59     33.61                34.0       4789.0          1175.0   
9        -114.60     34.83                46.0       1497.0           309.0   
10       -114.60     33.62                16.0       3741.0           801.0   
11       -114.60     33.60                21.0      

In [47]:
X = df.iloc[:,:-1].values
Y = df.iloc[:,8:].values

[[ 66900.]
 [ 80100.]
 [ 85700.]
 ...
 [103600.]
 [ 85800.]
 [ 94600.]]


In [50]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler(feature_range = (0,1))
X_after_min_max_scaler = min_max_scaler.fit_transform(X)

In [51]:
print(X_after_min_max_scaler)

[[1.         0.17534538 0.2745098  ... 0.02836402 0.07745437 0.06853009]
 [0.98406375 0.19766206 0.35294118 ... 0.03155918 0.07597435 0.09104012]
 [0.9750996  0.12221041 0.31372549 ... 0.00924914 0.01907581 0.07937822]
 ...
 [0.00498008 0.98831031 0.31372549 ... 0.03478236 0.07482322 0.1745769 ]
 [0.00498008 0.98405951 0.35294118 ... 0.03629586 0.07844105 0.10205376]
 [0.         0.8501594  1.         ... 0.02250624 0.04423615 0.17343209]]


In [79]:
from sklearn.model_selection import train_test_split
X_train , X_test , Y_train , Y_test = train_test_split(X_after_min_max_scaler,Y,test_size=0.3,random_state=1)

In [82]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train,Y_train)

LinearRegression()

In [84]:
Y_reg = reg.predict(X_test)
Y_reg

array([[269900.12587528],
       [292028.80761471],
       [269677.56453965],
       ...,
       [235529.12417858],
       [149029.30503213],
       [222232.77370834]])

In [85]:
Y_test

array([[288700.],
       [275000.],
       [263200.],
       ...,
       [183400.],
       [ 71300.],
       [195200.]])